### ISSUE TITLE
Compile Failure on Ubuntu Maverick

### ISSUE THREAD

**Issue by albertsj1** [PromyLOPh/pianobar#72]
Ever since I upgraded from Ubuntu 10.04 to 10.10, I'm unable to build pianobar.
I always get the following:

```
cc -std=c99 -O2 -DNDEBUG -I src/libpiano -I src/libwaitress \
                    -I src/libezxml -I /usr/include -I /usr/include -DENABLE_FAAD \
                    -I /usr/include -DENABLE_MAD -c -o src/libezxml/ezxml.o  src/libezxml/ezxml.c
cc -std=c99 -O2 -DNDEBUG src/main.o src/player.o src/settings.o src/terminal.o src/ui_act.o src/ui.o src/ui_readline.o src/libpiano/crypt.o src/libpiano/piano.o src/libpiano/xml.o src/libwaitress/waitress.o \
                    src/libezxml/ezxml.o -lao -lfaad -lmad \
                    -pthread -lm -o pianobar
/usr/lib/gcc/x86_64-linux-gnu/4.4.5/../../../../lib/libao.a(audio_out.o): In function `ao_shutdown':
(.text+0x252a): undefined reference to `dlclose'
/usr/lib/gcc/x86_64-linux-gnu/4.4.5/../../../../lib/libao.a(audio_out.o): In function `_append_dynamic_drivers':
(.text+0x2707): undefined reference to `dlopen'
/usr/lib/gcc/x86_64-linux-gnu/4.4.5/../../../../lib/libao.a(audio_out.o): In function `_append_dynamic_drivers':
(.text+0x276f): undefined reference to `dlsym'
/usr/lib/gcc/x86_64-linux-gnu/4.4.5/../../../../lib/libao.a(audio_out.o): In function `_append_dynamic_drivers':
(.text+0x279d): undefined reference to `dlsym'
/usr/lib/gcc/x86_64-linux-gnu/4.4.5/../../../../lib/libao.a(audio_out.o): In function `_append_dynamic_drivers':
(.text+0x27d3): undefined reference to `dlsym'
/usr/lib/gcc/x86_64-linux-gnu/4.4.5/../../../../lib/libao.a(audio_out.o): In function `_append_dynamic_drivers':
(.text+0x2809): undefined reference to `dlsym'
/usr/lib/gcc/x86_64-linux-gnu/4.4.5/../../../../lib/libao.a(audio_out.o): In function `_append_dynamic_drivers':
(.text+0x283f): undefined reference to `dlsym'
/usr/lib/gcc/x86_64-linux-gnu/4.4.5/../../../../lib/libao.a(audio_out.o):(.text+0x2875): more undefined references to `dlsym' follow
collect2: ld returned 1 exit status
make: *** [pianobar] Error 1
```

I have libao installed.

```
⚡ dpkg --get-selections | grep libao
libao-common                    install
libao-dev                   install
libao2                      deinstall
libao4                      install
```

Not sure what deinstall means, but libao-dev is installed, which I think is what needs to be installed, correct?

Thanks
