### ISSUE TITLE
implicit declaration of function ‘getline’

### ISSUE THREAD

**Issue by ryandesign** [PromyLOPh/pianobar#572]
pianobar fails to build on OS X 10.6 (and presumably earlier versions) because it uses `getline` which was added in OS X 10.7.

Here is a build log of the failure:

https://build.macports.org/builders/buildports-snowleopard-x86_64/builds/40083/steps/compile/logs/stdio

But the relevant errors are:

```
src/settings.c:216: warning: implicit declaration of function ‘getline’
```

```
Undefined symbols:
  "_getline", referenced from:
      _BarSettingsRead in settings.o
ld: symbol(s) not found
```

**Comment by PromyLOPh** [comment]
It’s probably not worth fixing. Snow Leopard’s support ended two years
ago.

**Comment by ryandesign** [comment]
I've taken over as maintainer of pianobar in MacPorts, so I'm coming back to this issue now.

It would be nice if you would reconsider your decision. There are lots of old Macs that cannot be upgraded to Lion or newer, but which would be perfectly adequate as music players. There are probably old versions of other operating systems that also lack `getline`. It is probably a simple matter to add a `getline` compatibility function; lots of other projects do so.

Here's a fresh build log:

https://build.macports.org/builders/ports-10.6_x86_64_legacy-builder/builds/8638/steps/install-port/logs/stdio

**Comment by PromyLOPh** [comment]
> There are probably old versions of other operating systems that also
> lack `getline`. It is probably a simple matter to add a `getline`
> compatibility function; lots of other projects do so.

Looking at [1] it seems fgets is available. So a patch like this one[2]
should work, doesn’t it?

[1] https://github.com/maxmind/geoipupdate/pull/4/commits/73e9a7f3476da0cf170ec0f2bb096af0ba8f8a82
[2] https://gist.github.com/ade9ed29fdcd9cbcb185a9303524c1a0

**Comment by PromyLOPh** [comment]
> There are probably old versions of other operating systems that also
> lack `getline`. It is probably a simple matter to add a `getline`
> compatibility function; lots of other projects do so.
Looking at [1] it seems fgets is available. So a patch like this one[2]
should work, doesn’t it?

[1] https://github.com/maxmind/geoipupdate/pull/4/commits/73e9a7f3476da0cf170ec0f2bb096af0ba8f8a82
[2] https://gist.github.com/ade9ed29fdcd9cbcb185a9303524c1a0

**Comment by ryandesign** [comment]
Thank you, yes, that does allow pianobar to work on Mac OS X 10.6, and I confirmed it still works with that patch on 10.11 as well.
