### ISSUE TITLE
error: implicit declaration of function 'av_channel_layout_describe' is invalid in C99

### ISSUE THREAD

**Issue by ryandesign** [PromyLOPh/pianobar#757]
### Subject of the issue
Building pianobar 2024.12.21 on macOS (with my patches from MacPorts to build correctly on macOS) with ffmpeg 4.4.5 fails for me. This is new; pianobar 2022.04.01 didn't have this problem. I assume I need a newer ffmpeg but your build system didn't check for the version of ffmpeg it requires and your README doesn't say what version it requires. Using ffmpeg 6.1.2 instead works.

### Your environment
* version of pianobar: 2024.24.21
* your Linux distribution and release version: macOS 12.7.5
* ffmpeg/libav version and the flags it was compiled with (if you compiled yourself): ffmpeg 4.4.5 compiled by MacPorts
* your config file: N/A

### Steps to reproduce
Compile pianobar 2024.12.21 with ffmpeg 4.4.5

### Expected behaviour
Successful build

### Actual behaviour
```
/usr/bin/clang -arch x86_64 -c -o src/player.o -Os -std=c99 -isystem/opt/local/include -I src/libpiano  -I/opt/local/libexec/openssl3/include  -I/opt/local/include/json-c  -MMD -MF src/player.d -MP src/player.c
src/player.c:286:2: error: implicit declaration of function 'av_channel_layout_describe' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        av_channel_layout_describe(&player->cctx->ch_layout, channelLayout, sizeof(channelLayout));
        ^
src/player.c:286:44: error: no member named 'ch_layout' in 'struct AVCodecContext'
        av_channel_layout_describe(&player->cctx->ch_layout, channelLayout, sizeof(channelLayout));
                                    ~~~~~~~~~~~~  ^
src/player.c:345:23: error: no member named 'ch_layout' in 'struct AVCodecParameters'
        aoFmt.channels = cp->ch_layout.nb_channels;
                         ~~  ^
src/player.c:594:42: error: no member named 'ch_layout' in 'struct AVFrame'
                const int numChannels = filteredFrame->ch_layout.nb_channels;
                                        ~~~~~~~~~~~~~  ^
4 errors generated.
```

**Comment by PromyLOPh** [comment]
https://github.com/PromyLOPh/pianobar/blob/master/INSTALL mentions you
need at least ffmpeg 5.1, which I believe is still correct.

**Comment by ryandesign** [comment]
Oh indeed; I had overlooked the INSTALL file.

**Comment by PromyLOPh** [comment]
I merged INSTALL into README, hoping that it will be more visible.
